// Generated by gencpp from file topic/time.msg
// DO NOT EDIT!


#ifndef TOPIC_MESSAGE_TIME_H
#define TOPIC_MESSAGE_TIME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace topic
{
template <class ContainerAllocator>
struct time_
{
  typedef time_<ContainerAllocator> Type;

  time_()
    : time(0.0)
    , sign(0)  {
    }
  time_(const ContainerAllocator& _alloc)
    : time(0.0)
    , sign(0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef uint8_t _sign_type;
  _sign_type sign;





  typedef boost::shared_ptr< ::topic::time_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::topic::time_<ContainerAllocator> const> ConstPtr;

}; // struct time_

typedef ::topic::time_<std::allocator<void> > time;

typedef boost::shared_ptr< ::topic::time > timePtr;
typedef boost::shared_ptr< ::topic::time const> timeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::topic::time_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::topic::time_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::topic::time_<ContainerAllocator1> & lhs, const ::topic::time_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.sign == rhs.sign;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::topic::time_<ContainerAllocator1> & lhs, const ::topic::time_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::topic::time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::topic::time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic::time_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::topic::time_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic::time_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::topic::time_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::topic::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f47d867e0932ea6a0ba2bc35171d3684";
  }

  static const char* value(const ::topic::time_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf47d867e0932ea6aULL;
  static const uint64_t static_value2 = 0x0ba2bc35171d3684ULL;
};

template<class ContainerAllocator>
struct DataType< ::topic::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "topic/time";
  }

  static const char* value(const ::topic::time_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::topic::time_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n"
"uint8 sign\n"
;
  }

  static const char* value(const ::topic::time_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::topic::time_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.sign);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct time_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::topic::time_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::topic::time_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "sign: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sign);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOPIC_MESSAGE_TIME_H
